version: '3.8'

services:
  memos_bot:
    image: memos_bot
    container_name: memos_bot
    ports:
      - "6666:6666"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/log:/app/log
    restart: always