version: '3.8'

services:
  memos_bot:
    image: memos_bot
    container_name: memos_bot
    ports:
      - "5005:5005"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /your_path:/app/log
    restart: always