spring:
  application:
    name: memos_bot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memos?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_username
    password: db_password
server:
  port: 5005

bot:
  token: your_bot_token